apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-e57s
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hngp-tenant/rhtap-demo-app/hacbs-test-project-e57s@sha256:bc33b67d64930ea2b29d2876c8ed7efb5f7b3f8884d01c31c17be092d8335ccd
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
